server:
  port: 8081

#database
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRE_DB:localhost:15432}/postgre_db?ssl=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
