version: "3.7"

volumes:
  csdata:
  pgdata:
  kafkaBrokerVolume:
  kafkaZookeeperVolume:
  kafkaZookeeperLogVolume:

networks:
  MyNetwork:
    driver: bridge
    name: MyNetwork

services:
# Kafka Service *******************************************************************************************
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    networks:
      - MyNetwork
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka

  zookeeper:
    image: 'bitnami/zookeeper:3.6.3'
    container_name: zookeeper
    volumes:
      - kafkaZookeeperVolume:/var/lib/zookeeper/data
      - kafkaZookeeperLogVolume:/var/lib/zookeeper/log
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - MyNetwork

  kafka:
    image: 'bitnami/kafka:3.1.0'
    container_name: kafka
    volumes:
      - kafkaBrokerVolume:/var/lib/kafka/data
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - MyNetwork

# Postgre Service *******************************************************************************************

  postgre_db:
    image: postgres:14-alpine
    container_name: postgre_db
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgre_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - MyNetwork


# Cassandra Service *******************************************************************************************
  mail_db:
    image: cassandra:3.11
    container_name: mail_db
    ports:
      - 9042:9042
    environment:
      HEAP_NEWSIZE: 1M
      MAX_HEAP_SIZE: 700M
    volumes:
      - csdata:/var/lib/cassandra
    networks:
      - MyNetwork


# Cloud Service *******************************************************************************************
  gateway:
    build: ./cloud_gateway
    image: gateway
    container_name: gateway
    ports:
      - 8080:8080
    networks:
      - MyNetwork
    environment:
      USER_S: user:8081
      PRODUCT_S: product:8082
      ORDER_S: order:8083
      MAIL_S: mail:8084

# Other Services *******************************************************************************************

  user:
    build: ./user
    image: user
    container_name: user
    depends_on:
      - postgre_db
    ports:
    - 8081:8081
    networks:
      - MyNetwork
    environment:
      POSTGRE_DB: postgre_db:5432

  product:
    build: ./product
    image: product
    container_name: product
    depends_on:
      - postgre_db
    ports:
      - 8082:8082
    networks:
      - MyNetwork
    environment:
      POSTGRE_DB: postgre_db:5432

  order:
    build: ./order
    image: order
    container_name: order
    depends_on:
      - postgre_db
    ports:
    - 8083:8083
    networks:
      - MyNetwork
    environment:
      POSTGRE_DB: postgre_db:5432
      MY_KAFKA: kafka:9092
      PRODUCT_S: product:8082


  mail:
    build: ./mail
    image: mail
    container_name: mail
    depends_on:
      - postgre_db
      - kafka
    ports:
    - 8084:8084
    networks:
      - MyNetwork
    environment:
      MY_KAFKA: kafka:9092
      MY_CASSANDRA: mail_db
      CASSANDRA_PORT: 9042
      PRODUCT_S: product:8082