server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user_id
          uri: http://${USER_S:localhost:8081}
          predicates:
            - Path=/user/**

        - id: product_id
          uri: http://${PRODUCT_S:localhost:8082}
          predicates:
            - Path=/product/**

        - id: order_id
          uri: http://${ORDER_S:localhost:8083}
          predicates:
            - Path=/order/**

        - id: mail_id
          uri: http://${MAIL_S:localhost:8084}
          predicates:
            - Path=/mail/**
