version: "3.7"

services:
#  product:
#    build: .
#    image: product
#    container_name: product
#    depends_on:
#      - product_db
#    ports:
#    - 8081:8081
#    networks:
#      - MyNetwork
#    environment:
#      PRODUCT_DB_IP: product_db:5432


  product_db:
    image: postgres:14-alpine
    container_name: product_db
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
      - MyNetwork


volumes:
  pgdata:

networks:
  MyNetwork:
    driver: bridge
    name: MyNetwork
